### ISSUE TITLE
TODO: Remove uname query parameter from join links

### ISSUE THREAD

**Issue by jrchamp** [ncstate-delta/moodle-mod_zoom#256]
According to Zoom Developer Support, the uname query parameter no longer does anything and can be safely removed.

**Comment by abias** [comment]
@jrchamp , I dare to say that this isn't true. Please try it yourself by adding the uname parameter to an ordinary Join Link URL. You will see that the uname Parameter defines the displayed name of the Zoom meeting participant. This is especially important for students who do not have a Zoom account (with a Zoom user profile and a display name) on their own and where Moodle defines the name how they appear in the meeting instead of relying that the student enters him proper name (and not Micky Mouse) when entering the meeting.

**Comment by jrchamp** [comment]
Thanks @abias 

I just confirmed that uname does still have an effect. For me, even though I have a Zoom account and was logged in, it overrode my name within the meeting. That's not necessarily a bad thing, but it means that Zoom Developer Support answered a different question than what I was asking.

I'll mark this closed for now.
