### ISSUE TITLE
Clear active user login session

### ISSUE THREAD

**Issue by satya-ip** [ncstate-delta/moodle-mod_zoom#32]
We are running into an issue with user name when student login to Zoom session from Moodle. If a user already have a Zoom login session in his computer with name ABC (probably logged in for a completely different purpose than Moodle session), but logged into Moodle as user XYZ, then the live session launched with this plugin will ignore XYZ (Moodle) name. 

We are trying to collect user duration in a session, but we are loosing the Moodle login name due to this.

Is there way to logout existing Zoom session (in desktop/whatever the device) and force Zoom to use the Moodle user name?

**Comment by Nicosoft** [comment]
Hi.

We had this issue.

By default, when you start the Zoom Meeting  from Moodle. In the link to start the meeting Moodle passes a ZPK (that linked to the logged Moodle User). If this ZPK is missing or expired, Zoom fallback on the Windows Zoom Client user.
This plugin stores the ZPK when the meeting is created but expired after 2 hours.

What to do: This required a code change, when the user click on 'Start Meeting' in Moodle a new ZPK should be generated on the fly instead of using the one stored in the database.
We fixed this issue by changing the code.

Hope this helps!

**Comment by satya-ip** [comment]
Thanks for quick response. I quickly checked latest version of this plugin code and I don't see usage of ZPK. Can you please point me to the file it is being generated?

**Comment by Nicosoft** [comment]
The ZPK is part of the start meeting url. Checkout in your database the values of the field named 'start_url'.
Here is an example from my database:
<pre>
https://zoom.us/s/123456789?zpk=j6UXbalblabalba
</pre>

**Comment by rlorenzo** [comment]
@Nicosoft Can you provide a patch or link to the fix you guys made?

**Comment by Rohanator9000** [comment]
@Nicosoft Were you able to implement forcing users to login? If so, did you do it with the 'enforce_login' API parameter?

**Comment by jrchamp** [comment]
Unless the meeting itself has been set to require users from a specific domain, I don't think there is a way for this plugin to force users who are already logged in to another Zoom account to switch accounts.
