### ISSUE TITLE
Feature Request: Recording links

### ISSUE THREAD

**Issue by jrchamp** [ncstate-delta/moodle-mod_zoom#46]
As far as I can tell, there is no database table or plugin code for pulling the recording information from Zoom and storing it in Moodle for the purpose of providing direct links in Moodle to Zoom Meeting Recordings.

We had this functionality with our previous web conferencing tool and we're already receiving requests for it with Zoom. Is this functionality something you would consider adding?

**Comment by rlorenzo** [comment]
@jrchamp We don't have cloud recording enabled or not encouraging it because we don't want to pay for the cloud storage. Do you have it enabled? 
If you want, we will be happy to include it in a pull request. But otherwise, we don't have it on our roadmap since we wouldn't be able to effectively use/test it.

**Comment by jrchamp** [comment]
@rlorenzo Yes, we do have it enabled and it has a few nice features (such as automatic transcripts). I am planning to implement something for our course management application, so I'll see what I can translate from that work to the Moodle Zoom plugin. Thank you for letting me know!

**Comment by kineoalexc** [comment]
Definitely a request from extended enterprise clients.  Would love to see it implemented

**Comment by Dextirpe** [comment]
I tested this version https://github.com/ucla/moodle-mod_zoom/tree/feature/CCLE-9504-show-zoom-recordings
It works! But you can't delete recordings and backup/restore fail.
